server {
    listen       80;
    server_name  localhost;
    root         /var/www/html/dist;
    location / {
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
    }
    # Allow access to .well-known directory for pwa and twa
    location ~ /\.well-known {
      allow all;
    }
    # restrict access to hidden files, just in case
    location ~ /\. {
      deny all;
    }
}